# Generated by Django 2.2.3 on 2020-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='isReply',
            field=models.BooleanField(default=False, verbose_name='is a reply ?'),
        ),
    ]
